### ISSUE TITLE
Fully rename unity_py to unity-sds-client in pypi and in various notebooks that use it

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-py#50]

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by anilnatha** [comment]
I've updated the package name and will issue a PR shortly. This ticket is part of the unity-py repo, we'll probably need to create a separate ticket if we don't have one already to track the changes for the sounder-sips-tutorial notebooks.

**Comment by rtapella** [comment]
https://github.com/unity-sds/sounder-sips-tutorial/pull/47
