### ISSUE TITLE
Support asset "roles" for STAC in Data Catalog data Searches

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-py#67]
STAC results from DAPA ciurrently utilize the asset keys of "data", "metadata", "browse", and a few others. This does not allow for the support of multiple data values without knowing their keys. To work around this, the asset key should be unique (based on the asset filename) and the asset-role will be added to indicate the _type_ of data: https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-roles

This means the code here:

https://github.com/unity-sds/unity-py/blob/main/unity_sds_client/services/data_service.py#L67-L71

Will need to be updated to A) iterate over the stac assets and create DataFiles instead of looking specifically for a asset with key `data`.

**Comment by rtapella** [comment]
get info from @ngachung

**Comment by rtapella** [comment]
- STAC asset key is not based on "data" or "metadata" - should be unique and not known ahead of time
- STAC asset role is used to define data, metadata, etc. (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-roles )
- Ingest commands can ingest multiple "data" role types successfully
- unity-py properly supports asset role (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-roles )
- file a ticket with CMR to use the asset-role in their results

**Comment by mike-gangl** [comment]
Can you provide an update on this ticket?

**Comment by GodwinShen** [comment]
@rtapella any updates here?  Is this resolved by PR https://github.com/unity-sds/unity-py/pull/73?

**Comment by anilnatha** [comment]
@GodwinShen Yes, PR #73 did resolve this ticket.
