### ISSUE TITLE
Add production configuration to unity-py

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-py#70]
Once deployed to unity-prod, populate the configration file with the appropriate cloudfront url and application token.

**Comment by rtapella** [comment]
@anilnatha needs sprint assigned

**Comment by rtapella** [comment]
needs the info from finishing: https://github.com/unity-sds/unity-project-management/issues/107

**Comment by mike-gangl** [comment]
I actually added this in the current STAC work we are doing. once that's merged, we'll have the appropriate operational configuration for production.

**Comment by rtapella** [comment]
part of https://github.com/unity-sds/unity-py/pull/73

**Comment by GodwinShen** [comment]
@rtapella looks like you guys worked that as part of https://github.com/unity-sds/unity-py/pull/73 and @mike-gangl approved that PR.  Is there anything else left to do for this ticket?
