### ISSUE TITLE
Test STAC Browser using unity-py command to generate a token to input into the form for authentication

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-py#77]
- part of https://github.com/unity-sds/unity-project-management/issues/117

**Comment by rtapella** [comment]
- [ ] can I see the available STAC catalogs?
- [ ] can I see the Collections in a catalog?
- [ ] can I search the Collections?
- [ ] can I find an individual file/asset that I am interested in?
- [ ] can I get pertinent info on asset to use it as an input for a Run/Job
- [ ] can I download an individual file of interest
- [ ] can I download a set of files of interest (e.g. a Collection of files)

**Comment by rtapella** [comment]
s = Unity(UnityEnvironments.TEST)
token = s._session.get_auth().get_token()

**Comment by rtapella** [comment]
Waiting until @wphyojpl gets a STAC Browser working with Cognito on a DAPA endpoint.

**Comment by rtapella** [comment]
seems to work for me

**Comment by GodwinShen** [comment]
@rtapella cool, it works for me as well in the unity-venue-test JupyterHub environment using python requests library and the unity-sds-client inside a python notebook!  What is left to do on this ticket now that we have the token stuff working?

**Comment by rtapella** [comment]
This is waiting on the STAC browser web-GUI to be set up and then try this same approach in the GUI instead of the CLI. The CLI shows that the token stuff is working and the endpoint is functional, but we’ll need to test the wiring.

**Comment by rtapella** [comment]
this is working now.. some oddities but it basically works!
