### ISSUE TITLE
Unity Py Updates

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-py#8]

**Comment by rtapella** [comment]
https://lucid.app/lucidchart/9d32bd5b-41a5-4e9a-8970-843bd39062fe/edit?invitationId=inv_0b3c6e30-ced7-4456-8149-2d567a766939&page=Gkyl6LvXEhB1#

**Comment by mike-gangl** [comment]
Not enough detail to keep this ticket open.
