### ISSUE TITLE
Add unity.py display of basic service-status in a venue

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-py#86]
When you “print” the configuration info with endpoints, also show the status of each endpoint (basic health: good/bad)

See https://github.com/unity-sds/unity-ui/issues/25

**Comment by mike-gangl** [comment]
If we go this route, the config printed should only be for an active environment (dev, test, prod), and a project/venue will need to be defined. Otherwise health endpoints don't make much sense here.

**Comment by rtapella** [comment]
we could also go the path of a HealthService
so you'd make a new health_service and then either print it or do get_health()

**Comment by rtapella** [comment]
Current thinking is that for now we just have the one HealthService and get a consolidated set of health info from that (similar to how the web app will work).

Future potential: you can ask a particular service (e.g. a ProcessService) what it's individual health is.

**Comment by GodwinShen** [comment]
@anilnatha and @rtapella ping for status.

**Comment by rtapella** [comment]
Has not been started yet. Anil is out this week so probably will get pushed out.
I may look at it if I have time but that is unlikely because I have other stuff to do this sprint

**Comment by rtapella** [comment]
There is a draft of this with the stub json data
Will need to be updated with real endpoint when it's ready

**Comment by rtapella** [comment]
waiting for https://github.com/unity-sds/unity-cs/issues/381 to wrap up

**Comment by rtapella** [comment]
Closing the initial work with stub json.
Remaining work in #91
