### ISSUE TITLE
Add app-pack-gen build to Unity py

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-py#87]
add to the "application" services within unity py the abilty to request an application build.

The required inputs (currently) for app-pack-gen calls are the repository to be built. The url of the build needs to be figured out with @edwinsarkissian and @mcduffie but currently i think its:

```
/ads/mcp-clone
```

and requires the auth header, json content type, and the 'clone_url' header to execute correctly.

Example of the clone_url value is `https://github.com/unity-sds/unity-example-application`

**Comment by rtapella** [comment]
Some questions:
- long-term, this will point to the app catalog (Dockstore) to get the repo name/tag/version, correct?
- do we expect near-term that applications will be at the top-level of the unity-sds organization?

**Comment by mike-gangl** [comment]
> Some questions:
> 
> * long-term, this will point to the app catalog (Dockstore) to get the repo name/tag/version, correct?
> * do we expect near-term that applications will be at the top-level of the unity-sds organization?

What do you mean "top level" unity-sds org? in Github? the code can be anywhere in github- outside our org would be preferable.

**Comment by rtapella** [comment]
By top level I mean:
https://github.com/unity-sds/unity-example-application
(the application is at the same "level" in github as, say, a unity-data-services or unity-sps)

vs.
https://github.com/unity-sds/apps/unity-example-application
(some place to put "applications" within the unity-sds organization)
(where is there a "catalog" of these?)

(also... I am getting confused... these applications are the "algorithms"... app packages that run in SPS, right? These are not the management-console "applications")

**Comment by rtapella** [comment]
@mike-gangl @anilnatha who will actually do this work with unity-py?
Is it something that James' team should work on? Is it important to knock this out during this sprint (vs other priorities)

**Comment by mcduffie** [comment]
This would essentially be a wrapper around a REST call. See: https://docs.google.com/document/d/15oT2unTgZkhaXIVTva3BNZAA9O5etRsf/edit ~ page 18.

**Comment by GodwinShen** [comment]
@rtapella ping for status.

**Comment by rtapella** [comment]
likely to push out. the health-status feature of unity.py is higher priority

**Comment by rtapella** [comment]
This could be a bigger deal than just wrapping a RESTful endpoint. need to look into it more. 

It does make sense to be in unity.py though

**Comment by rtapella** [comment]
blah = new Application()

application.register("some parameter / url?")

**Comment by rtapella** [comment]
@mcduffie we only need the Cognito token for authentication, correct? (not github etc.)

Then we just need to pass in the code repo URL as the argument, right? Do we need to pass in a branch name?

**Comment by rtapella** [comment]
And it places the App Package in Dockstore, right?
What's returned by the API? The Dockstore URL? CWL URL?

**Comment by mcduffie** [comment]
Yes you only need Cognito authorization. It doesn't return anything useful yet.

**Comment by rtapella** [comment]
Likely to push this out a sprint

**Comment by rtapella** [comment]
This is high priority for the start of sprint 24.3.2

**Comment by rtapella** [comment]
https://github.com/unity-sds/unity-monorepo/tree/apgs-client

**Comment by rtapella** [comment]
this is done and merged into monorepo
it is part of unity-sds-client 0.6.0
