### ISSUE TITLE
Test unity.py execute and status with Airflow WPST wrapper

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-py#88]
depends on: 
- https://github.com/unity-sds/unity-sps/issues/62
- https://github.com/unity-sds/unity-sps/issues/61
- update unity-py to include the OGC-Processes python library

https://github.com/unity-sds/unity-py/blob/ogc-processes-api/examples/ogc_notebook.ipynb

**Comment by rtapella** [comment]
This is a bit more complex than initially anticipated. Instead of just using WPS-T, the new api conforms to OGC Processes API.

Additionally, Drew has built a python API to OGC Processes directly, and we will wrap that python library with unity-sds-client / Unity-py. So there are a few layers to update before we can test

**Comment by GodwinShen** [comment]
@rtapella is this related to the new work ticket that @mike-gangl just created: https://github.com/unity-sds/unity-sps-ogc-processes-api-client-python/issues/4?

**Comment by rtapella** [comment]
Waiting for #89 to complete

**Comment by rtapella** [comment]
Yes this is an older ticket but there was a missing step that Mike’s working on before we can actually do this, due to a change in how we had expected SPS to implement this vs. the actual

**Comment by rtapella** [comment]
I think this may be unblocked but may need to slip into next week.

**Comment by GodwinShen** [comment]
@rtapella ping for status.

**Comment by rtapella** [comment]
this is still Blocked. chatting w/ Mike to figure out when to test

**Comment by rtapella** [comment]
@mike-gangl : "there is a dev instance available in sbg-dev"
"you can attempt to run against that using the unity-py `dev`"
"there is a notebook that does this somewhat already: https://github.com/unity-sds/unity-py/blob/ogc-processes-api/examples/ogc_notebook.ipynb"
""getting" items from OGC works fine, but we're not currently able to affect change (that is, deploy an app or run a random app from the dockstore)"

**Comment by rtapella** [comment]
also see: https://github.com/unity-sds/unity-py/issues/89#issuecomment-2135795646

**Comment by rtapella** [comment]
this should be ready to completely test this sprint

**Comment by rtapella** [comment]
bumping out due to status of API vs. Mike's vacation

**Comment by rtapella** [comment]
execute() and status() are good
